apiVersion: kafka.strimzi.io/v1beta2
kind: KafkaBridge
metadata:
  generation: 1
  managedFields:
    - apiVersion: kafka.strimzi.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        'f:spec':
          .: {}
          'f:bootstrapServers': {}
          'f:enableMetrics': {}
          'f:http':
            .: {}
            'f:port': {}
          'f:replicas': {}
      manager: Mozilla
      operation: Update
    - apiVersion: kafka.strimzi.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        'f:status':
          .: {}
          'f:conditions': {}
          'f:labelSelector': {}
          'f:observedGeneration': {}
          'f:replicas': {}
          'f:url': {}
      manager: strimzi-cluster-operator
      operation: Update
      subresource: status
  name: my-bridge
  namespace: kafka-ns
  resourceVersion: '58250'
spec:
  bootstrapServers: 'my-cluster-kafka-bootstrap:9092'
  enableMetrics: true
  http:
    port: 8080
  replicas: 1
